name: Deploy 11ty to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.set-artifact-name.outputs.name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate unique artifact name
        id: set-artifact-name
        run: |
          UNIQUE_NAME="github-pages-$(date +%s)"
          echo "name=$UNIQUE_NAME" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: NODE_ENV=production npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'
          # name: ${{ steps.set-artifact-name.outputs.name }} # ĐÃ COMMENT DÒNG NÀY

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4